# yaml-language-server: $schema=../schemas/config.json
target: csharp
known_types:
  - ident
namespace: Scover.Psdc.Parsing
modifiers:
  ?:
    type: Option<$1>
    none_when: '!$1.HasValue'
    unwrap: $1.Value
root: node
common_props:
  location: range
